import 'dart:convert';

/// A single flashcard item generated by the RAG pipeline.
class RagFlashcardItem {
  final String id;
  final String wordHindi;
  final String wordMundari;
  final String meaningHindi;
  final String meaningMundari;
  final String emoji;
  final String? imageAsset;

  RagFlashcardItem({
    required this.id,
    required this.wordHindi,
    required this.wordMundari,
    required this.meaningHindi,
    required this.meaningMundari,
    required this.emoji,
    this.imageAsset,
  });

  factory RagFlashcardItem.fromJson(Map<String, dynamic> json) =>
      RagFlashcardItem(
        id: json['id'] as String? ?? '',
        wordHindi: json['word'] as String? ?? '',
        wordMundari: json['word_mundari'] as String? ?? json['word'] as String? ?? '',
        meaningHindi: json['meaning'] as String? ?? '',
        meaningMundari: json['meaning_mundari'] as String? ?? json['meaning'] as String? ?? '',
        emoji: json['emoji'] as String? ?? '✨',
        imageAsset: json['imageAsset'] as String? ?? json['image_path'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'word': wordHindi,
        'word_mundari': wordMundari,
        'meaning': meaningHindi,
        'meaning_mundari': meaningMundari,
        'emoji': emoji,
        if (imageAsset != null) 'imageAsset': imageAsset,
      };
}

/// A full set of RAG-generated flashcards for a chapter.
class RagFlashcardSet {
  final String id;
  final String title;
  final String chapterName;
  final List<RagFlashcardItem> cards;

  RagFlashcardSet({
    required this.id,
    required this.title,
    required this.chapterName,
    required this.cards,
  });

  factory RagFlashcardSet.fromJson(Map<String, dynamic> json) =>
      RagFlashcardSet(
        id: json['id'] as String? ?? '',
        title: json['title'] as String? ?? '',
        chapterName: json['chapterName'] as String? ?? '',
        cards: (json['cards'] as List<dynamic>?)
                ?.map((e) => RagFlashcardItem.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'chapterName': chapterName,
        'cards': cards.map((c) => c.toJson()).toList(),
      };

  String toFormattedJson() => const JsonEncoder.withIndent('  ').convert(toJson());
}
